### ISSUE TITLE
String added to list lost.

### ISSUE THREAD

**Issue by atfornes** [P2Pvalue/incubator-wave#6]
Using the API, a string is missed when added to a recently created and attached list. 

Steps to reproduce issue:

1 open a model and register some events: 
```javascript
      window.WaveJS.openModel(
        window.configTimelineTests.testimoniesWaveId,
        function (model) {
          window.WaveJS.model = model;
          ...
          //register some events 
          model.root.get($scope.userId).registerEventHandler(
          ...
```

2 create a string, create a list, attach it to the root map and add the string to the list
```javascript
      var str = window.WaveJS.model.createString(s);
      var list =  window.WaveJS.model.createList();
      var map = window.WaveJS.model.root;
      list = map.put(receiver,list);
      list.add(str);
```

3 try to access that string from the API after refreshing or using another tab or browser or comuter...
result: the list is attached to the root map as expected **but the string is missing!**

note: trying to access the string from the context (browser's tab) where it was created succed, i.e. it is in the client model but the change has not been propagated.

**Comment by pablojan** [comment]
I couldn't reproduce it. A new deep example of  APIs is available here https://github.com/P2Pvalue/swell-showcase/tree/master/swell-list

In addition, some Wave editing callbacks has been added to the API, they can help you to debug
https://github.com/P2Pvalue/incubator-wave#general-api-callbacks

**Comment by pablojan** [comment]
A full review and deep changes of the underlying generic data model implementation have been done. All wave data generated with previous version of API is not longer supported.
